### ISSUE TITLE
Alternative WebUI is enabled

### ISSUE THREAD

**Issue by Asuanin** [iFelix18/Dark-qBittorrent-WebUI#1]
Hi, do you planed this webUI style port to separated "Alternate WebUI" using qBittorrent's Web API?

https://github.com/qbittorrent/qBittorrent/pull/7610
https://github.com/qbittorrent/qBittorrent/wiki/Alternate-WebUI-usage

**Comment by iFelix18** [comment]
At the moment... no, but I do not exclude it. Probably in future.

**Comment by Asuanin** [comment]
Thanks for your answer

**Comment by iFelix18** [comment]
Reopen. It's a good idea anyway, so I remember it for the future.

**Comment by disrupted** [comment]
that would be great !

**Comment by iFelix18** [comment]
Refer to the new updated readme
