### ISSUE TITLE
Error in login page after applying Alternative WebUI

### ISSUE THREAD

**Issue by dmz-madrid** [iFelix18/Dark-qBittorrent-WebUI#3]
On Raspbian Buster, installed qBittorrent with
`sudo apt-get install qbittorrent-nox`
changed the WebUI to Dark-qBittorrent successfully but at the next login attempt, instead of login input it says:

> Unacceptable file type, only regular file is allowed.

Solution was [here ](https://github.com/qbittorrent/qBittorrent/issues/10503#issuecomment-486923269) renaming <new folder>/public/index.html to <new folder>/public/login.html

**Comment by iFelix18** [comment]
This should now be [fixed](https://github.com/qbittorrent/qBittorrent/issues/10503#issuecomment-488934137)
